### PR TITLE
New sample: Line of sight (location)

### PR DESCRIPTION
**Pull request by gdhakal**
This sample demonstrates how to interactively place a line of sight between two locations.

### CODE REVIEW

**Comment by gdhakal** [comment]
Need to revisit this sample given the changes made to iOS sample.

**Comment by dg0yal** [comment]
@gdhakal assigning this to you till you are ready for it to be reviewed (after making changes to match iOS). Also, take a look at the thumbnail images and see if they are configured properly. When I was looking at this branch I didn't see the thumbnail showup in the sample box

**Comment by gdhakal** [comment]
@nixta over to you to merge.

**Comment by nixta** [comment]
Ok, @gdhakal, I'm sorry. One last change to work with 100.2.1 (click to place observer, move mouse to update target). I also noticed the thumbnails weren't quite right. Please take a look and let me know.

**Comment by gdhakal** [comment]
@nixta As discussed, I have made the changes to `README`.

**Pull request merged**
