### PR TITLE
New sample: Animate 3D symbols

### PR DESCRIPTION
**Pull request by singhgag**

### CODE REVIEW

**Comment by dg0yal** [comment]
Can we get the numbers to be fixed width or columns so that they don't jiggle when updating?
jiggling-numbers

**Comment by dg0yal** [comment]
Also, can we add user options for auto-heading/pitch/roll. I feel like that is functionality we should showcase

**Comment by dg0yal** [comment]
Also, would be good to add units (Meters, degrees, etc etc) to these settings
image

**Comment by dg0yal** [comment]
That's it. Code looks really good.

**Comment by singhgag** [comment]
Thanks for the feedback @dg0yal. I have made the changes, please verify.

**Comment by dg0yal** [comment]
Please put this in the v.next branch

**Comment by singhgag** [comment]
@dg0yal Good catch. I have updated the base branch for the pull request. Don't merge this yet. I am waiting on some changes in core due this week.

**Pull request merged**
